<a href="https://colab.research.google.com/github/Shandeepsugumar/Data-mining/blob/main/Fictional_Character_Battle_Outcome_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import pandas as pd

In [ ]:
file_path='/content/drive/MyDrive/dm/DM.csv'
df=pd.read_csv(file_path)
print(df)

          Character   Universe  Strength  Speed  Intelligence  \
0      Wonder Woman     Marvel       7.0    8.0             3   
1          Iron Man     Marvel       4.0    7.0             9   
2          Iron Man  DC Comics       8.0    7.0             5   
3        Spider-Man  DC Comics       5.0    6.0            10   
4             Flash     Marvel       7.0    6.0             2   
..              ...        ...       ...    ...           ...   
94       Spider-Man  DC Comics       7.0    7.0             5   
95     Wonder Woman  DC Comics      10.0    4.0             1   
96     Wonder Woman  DC Comics       9.0    4.0             6   
97             Thor     Marvel       7.0    8.0             6   
98  Captain America     Marvel       9.0    8.0             3   

   SpecialAbilities    Weaknesses  BattleOutcome  
0       Telekinesis    Kryptonite            0.0  
1       Telekinesis    Kryptonite            0.0  
2       Telekinesis         Magic            0.0  
3       Telekin

In [ ]:
df.isnull().sum()

Character           3
Universe            1
Strength            1
Speed               1
Intelligence        0
SpecialAbilities    1
Weaknesses          1
BattleOutcome       2
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.drop_duplicates(inplace=True)

In [9]:
df1 = df['Intelligence']
a = df1.sort_values(ascending=0)
len1 = df1.index.size
len2 = len1//4
import numpy as np
arr = list(np.array(df1.head(len1)))
arr.sort()
print(arr)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]


In [10]:
print('The Array of Intelligence is ',arr,"\n")
bin_1 = np.array(arr[:len2])
len3 = len2 + len2
bin_2 = np.array(arr[len2:len3])
len4 = len3 + len2
bin_3 = np.array(arr[len3:len4])
bin_4 = np.array(arr[len4:])
mh1 = bin_1[0]
mh2 = bin_2[0]
mh3 = bin_3[0]
mh4 = bin_4[0]
print("The Actual Bins that are fabricated:\n")
print(bin_1)
print(bin_2)
print(bin_3)
print(bin_4)
bin1 = bin_1
bin2 = bin_2
bin3 = bin_3
bin4 = bin_4
m1 = np.mean(bin1)
m2 = np.mean(bin2)
m3 = np.mean(bin3)
m4 = np.mean(bin4)
for i in range(len(bin1)):
  bin1[i] = m1
for i in range(len(bin2)):
  bin2[i] = m2
for i in range(len(bin3)):
  bin3[i] = m3
for i in range(len(bin4)):
  bin4[i] = m4
print('\nBinning by Mean Method:\n')
print(bin1)
print(bin2)
print(bin3)
print(bin4)
bin1 = bin_1
bin2 = bin_2
bin3 = bin_3
bin4 = bin_4
md1 = np.median(bin1)
md2 = np.median(bin2)
md3 = np.median(bin3)
md4 = np.median(bin4)
for i in range(len(bin1)):
  bin1[i] = md1
for i in range(len(bin2)):
  bin2[i] = md2
for i in range(len(bin3)):
  bin3[i] = md3
for i in range(len(bin4)):
  bin4[i] = md4

print('\nBinning by Median Method:\n')
print(bin1)
print(bin2)
print(bin3)
print(bin4)


for i in range(len(bin1)-1):
  bin_1[i] = mh1
for i in range(len(bin2)-1):
  bin_2[i] = mh2
for i in range(len(bin3)-1):
  bin_3[i] = mh3
for i in range(len(bin4)-1):
  bin_4[i] = mh4
print('\nBinning by Boundaries Method:\n')
print(bin_1)
print(bin_2)
print(bin_3)
print(bin_4)

The Array of Intelligence is  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10] 

The Actual Bins that are fabricated:

[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 3 3 3 3 3 3 4]
[4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6]
[6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 8 8 8 8]
[ 8  8  8  8  8  9  9  9  9  9  9  9  9  9  9 10 10 10 10 10 10 10 10 10
 10 10 10]

Binning by Mean Method:

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]

Binning by Median Method:

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[6 6 6 6 6 6 6 6 6 6 6 6 6